version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: motarilog_db
    ports:
      - "27017:27017"
    volumes:
      - motarilog-data:/data/db
    networks:
      - motarilog-network

  backend:
    build: .
    container_name: motarilog_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./backend/static/uploads:/app/backend/static/uploads
    networks:
      - motarilog-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/motarilog
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      # REPLACE THIS BOT TOKEN
      - TELEGRAM_BOT_TOKEN=----------REPLACEME----------------

  # --- NEW BOT SERVICE ---
  bot:
    build: .
    container_name: motarilog_bot
    depends_on:
      - mongo
    networks:
      - motarilog-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/motarilog
      # SAME TOKEN HERE
      - TELEGRAM_BOT_TOKEN=---------REPLACEME----------------
    # Run the bot script instead of Flask
    command: ["python", "backend/bot_service.py"]

volumes:
  motarilog-data:

networks:
  motarilog-network:
    driver: bridge
